# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
# ko:
#   languageCode: ko-kr


languages:
  ko:
    languageCode: ko-
    weight: 1
  en:
    languageCode: en
    weight: 2

# languages:
#   ko:
#     languageCode: ko-
#     languageName: 한국어
#     weight: 1
#     # contentDir: content/ko
#   en:
#     languageCode: en
#     languageName: English
#     weight: 2
#     # contentDir: content/en

#   #Uncomment for multi-lingual sites, and move Korean content into `ko` sub-folder.
#   #contentDir: content/ko

# <nav>
#   <ul>
#     {{ range .Site.Languages }}
#       <li><a href="{{ .Permalink }}">{{ .LanguageName }}</a></li>
#     {{ end }}
#   </ul>
# </nav>


# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
